Add support for generic SPI NOR flash and the GD25Q128 on Rock64
ayufan-rock64/linux-kernel pull request #2
Opened 2017-07-02 20:31 UTC by xalius

Rock64 has a GD25Q128 SPI NOR Flash device, add support for mtd devices and generic NOR drivers.

2017-07-02 20:33 UTC, ayufan requested changes

2017-07-02 20:33 UTC, ayufan commented on arch/arm64/boot/dts/rockchip/rk3328.dtsi
> +		status = "okay";
Please enable this in `rock64.dts`.

```
&spi0 {
  status = "okay";
};

2017-07-02 20:33 UTC, ayufan commented on arch/arm64/boot/dts/rockchip/rk3328.dtsi
> +		/* dmas = <&dmac 8>, <&dmac 9>; */
I believe that you should be able to remove these keys too from rock64.dts. Or maybe we should just "zero" them?

2017-07-02 20:33 UTC, ayufan commented on arch/arm64/configs/rockchip_linux_defconfig
> -CONFIG_USB_ACM=m
Why we removed that?

2017-07-03 15:53 UTC, xalius commented
Cleaned that up a little, I don't know where the two stray config changes came from, but they are gone now :-), removing dt properties via /delete-properties/  works, I haven't found a nicer way to disable DMA...

2017-07-03 16:13 UTC, ayufan approved these changes

2017-07-03 16:13 UTC, merged